# Generated by Django 6.0.4 on 2026-05-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathch_number', models.CharField(max_length=100, verbose_name='Номер партии')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в этом филиале')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно для продажи')),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складах',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название поставщика')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание поставщика')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='InventoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INCOME', 'Приход от поставщика'), ('WRITE_OFF', 'Списание (брак/порча)'), ('RETURN', 'Возврат поставщику')], max_length=10, verbose_name='Тип документа')),
                ('number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Проведен')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.branch')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space')),
            ],
            options={
                'verbose_name': 'Документ движения товара',
                'verbose_name_plural': 'Документы движения товара',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invertory.inventorydocument')),
            ],
            options={
                'verbose_name': 'Позиция документа',
                'verbose_name_plural': 'Позиции документов',
            },
        ),
    ]
