# Generated by Django 6.0.4 on 2026-05-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invertory', '0001_initial'),
        ('recepts', '0001_initial'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.recepts'),
        ),
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='space.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='stock',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='recepts.recepts', verbose_name='Лекарство'),
        ),
        migrations.AddField(
            model_name='stock',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='space.space', verbose_name='Аптека'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='space.space', verbose_name='Аптека'),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invertory.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('branch', 'recept')},
        ),
    ]
