name: apteka_erp 

services:
  
  db:
    image: postgres:16-alpine
    container_name: pharmacy_postgres_db
    environment:
      POSTGRES_DB: Apteka
      POSTGRES_USER: zero
      POSTGRES_PASSWORD: "0526"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Контейнер для Redis
  redis:
    image: redis:7-alpine
    container_name: pharmacy_redis
    ports:
      - "6379:6379"
    restart: always

  # Контейнер твоего Django бэкенда (ERP Аптека)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: erp_apteka:latest
    container_name: erp_django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres_data: