# Generated by Django 6.0.4 on 2026-05-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-адрес категории')),
                ('spaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='space.space', verbose_name='Аптеки')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название производителя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание производителя')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна производителя')),
                ('spaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='space.space', verbose_name='Аптеки')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Recepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название лекарства')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('barcode', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Штрихкод')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/', verbose_name='Фото')),
                ('is_prescription_required', models.BooleanField(default=False, verbose_name='По рецепту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepts', to='recepts.category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepts', to='recepts.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Справочник лекарств',
                'verbose_name_plural': 'Справочник лекарств',
            },
        ),
    ]
