# Generated by Django 6.0.4 on 2026-05-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepts',
            name='barcode',
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Штрихкод')),
                ('volume', models.CharField(blank=True, max_length=255, null=True, verbose_name='Объем/дозировка')),
                ('unitmeas', models.CharField(blank=True, choices=[('MG', 'мг'), ('ML', 'мл')], max_length=10, null=True, verbose_name='единица измерения')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='recepts.recepts', verbose_name='Лекарство')),
            ],
            options={
                'verbose_name': 'Штрихкoд',
                'verbose_name_plural': 'Штрихкоды',
            },
        ),
    ]
