# Generated by Django 6.0.4 on 2026-05-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0002_remove_recepts_barcode_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объем'),
        ),
    ]
