# Generated by Django 6.0.4 on 2026-06-02 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0003_alter_barcode_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode', to='recepts.recepts', verbose_name='Лекарство'),
        ),
        migrations.AlterField(
            model_name='recepts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='recepts.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recepts',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='recepts.manufacturer', verbose_name='Производитель'),
        ),
    ]
