# Generated by Django 6.0.4 on 2026-05-09 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото')),
                ('position', models.CharField(choices=[('MANAGER', 'Менеджер'), ('PHARMACIST', 'Фармацевт'), ('CASHIER', 'Кассир'), ('WAREHOUSE_WORKER', 'Работник склада'), ('OTHER', 'Другое')], max_length=255)),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Контактная информация')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Навыки и компетенции')),
                ('iin', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИИН паспорта')),
                ('year_of_birth', models.DateField(blank=True, null=True, verbose_name='Год рождения')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата найма')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='space.space')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
