# Generated by Django 6.0.4 on 2026-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employees_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('MANAGER', 'Менеджер'), ('ADMIN', 'Администратор'), ('PHARMACIST', 'Фармацевт')], default='PHARMACIST', max_length=255, verbose_name='должность'),
        ),
    ]
