# Generated by Django 6.0.4 on 2026-05-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepts', '0001_initial'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер чека')),
                ('number_kassa', models.CharField(max_length=50, verbose_name='Номер кассы')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая сумма')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_checks', to='space.branch', verbose_name='Филиал')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_checks', to='space.space', verbose_name='Аптека')),
            ],
            options={
                'verbose_name': 'Заголовок чека',
                'verbose_name_plural': 'Заголовки чеков',
            },
        ),
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_items', to='recepts.recepts', verbose_name='Лекарство')),
                ('header_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.headercheck', verbose_name='Заголовок чека')),
            ],
            options={
                'verbose_name': 'Позиция чека',
                'verbose_name_plural': 'Позиции чеков',
            },
        ),
    ]
