# Generated by Django 6.0.4 on 2026-05-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercheck',
            name='total_product',
            field=models.PositiveBigIntegerField(default=0, verbose_name='общее количество продуктов'),
        ),
    ]
