# Generated by Django 6.0.4 on 2026-05-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_headercheck_total_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headercheck',
            name='total_product',
        ),
    ]
